# ===================================================================
# Spring Boot configuration.
#
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 9001

logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: INFO
    com.beerhouse: DEBUG

spring:
  profiles:
    active: test
  jmx:
    enabled: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./h2db/BeerDB_test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    database-platform: io.github.jhipster.domain.util.FixedH2Dialect
    open-in-view: false
    properties.hibernate.ddl-auto: create-drop
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      console-available: true

jhipster:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  cors:
    allowed-origins: '*'
    allowed-methods: 'GET,POST,PUT,PATCH,DELETE'
    allowed-headers: '*'
    allow-credentials: true
    max-age: 1800