server:
  port: 9000

spring:
  application:
    name: Craft-Beer

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./BeerDB;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      poolName: Hikari
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        id.new_generator_mappings: true
        dialect: org.hibernate.dialect.H2Dialect
        cache.use_second_level_cache: true
