server:
  port: 9000
  context-path: /beerhouse

spring:
  application:
    name: Craft-Beer

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./h2.db
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      poolName: Hikari
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
